// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj_5ChEh8cg55_r3HEkS5aTpf3AO_wnz8',
    appId: '1:263236169738:web:ff08c1b163727da539eff3',
    messagingSenderId: '263236169738',
    projectId: 'csc322-game-app-af459',
    authDomain: 'csc322-game-app-af459.firebaseapp.com',
    storageBucket: 'csc322-game-app-af459.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXy6Jyw9-CNVHeSfATSJkABBYl3M5cwMY',
    appId: '1:263236169738:android:94db3034d30d8b3039eff3',
    messagingSenderId: '263236169738',
    projectId: 'csc322-game-app-af459',
    storageBucket: 'csc322-game-app-af459.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIoDeP_DFDadnbC67q_x0__ScAwSns6gk',
    appId: '1:263236169738:ios:d3d27987f8a0b6b839eff3',
    messagingSenderId: '263236169738',
    projectId: 'csc322-game-app-af459',
    storageBucket: 'csc322-game-app-af459.appspot.com',
    iosBundleId: 'com.example.csc322GameApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIoDeP_DFDadnbC67q_x0__ScAwSns6gk',
    appId: '1:263236169738:ios:681c94282eacec1e39eff3',
    messagingSenderId: '263236169738',
    projectId: 'csc322-game-app-af459',
    storageBucket: 'csc322-game-app-af459.appspot.com',
    iosBundleId: 'com.example.csc322GameApp.RunnerTests',
  );
}
